// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

void main() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl2G8yQvNThHTgM-j7OPqgs52Vy1QV7BY',
    appId: '1:587003715617:android:50520e622020cb09b38360',
    messagingSenderId: '587003715617',
    projectId: 'prova-fe9b2',
    databaseURL:
        'https://prova-fe9b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prova-fe9b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8pGXs9q52QHWFirJtVFyE2QyBaBZZDjQ',
    appId: '1:587003715617:ios:9efb4c3b4ae1e031b38360',
    messagingSenderId: '587003715617',
    projectId: 'prova-fe9b2',
    databaseURL:
        'https://prova-fe9b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prova-fe9b2.appspot.com',
    iosClientId:
        '587003715617-a255jqvgf26v9c9ane9hub9jk9upeav6.apps.googleusercontent.com',
    iosBundleId: 'com.example.planup',
  );
}
